import type { MenuBarCountdownMode, MenuBarStyle, Prayer } from "./types";

export type SupportedLanguage = "en" | "ar" | "tr" | "bn";
export type LanguageSelection = SupportedLanguage | "system";

type TranslationValue = string | ((vars: Record<string, string | number>) => string);

const translations = {
  en: {
    appTitle: "Prayer Times for Windows",
    waiting: "Waiting",
    general: "General",
    locationTime: "Location & Time",
    calculation: "Calculation",
    notifications: "Notifications",
    focusMode: "Focus Mode",
    nextPrayer: "Next prayer",
    next: "Next",
    in: "in",
    focusNow: "Focus now",
    stop: "Stop",
    settings: "Settings",
    quit: "Quit",
    startup: "Startup",
    launchAtLogin: "Launch at login",
    desktopWidget: "Desktop widget",
    showFloatingWidget: "Show floating widget",
    widgetDescription: "Desktop widget with next prayer time and countdown.",
    widgetControls: "Widget controls",
    widgetControlsHelp: "Drag the widget from its body. Use the X button to hide it.",
    showNow: "Show now",
    menuBar: "Tray label",
    labelStyle: "Label style",
    countdownShows: "Countdown shows",
    panel: "Panel",
    showIshraqTime: "Show Ishraq time",
    showHijriDate: "Show Hijri date",
    hijriAdjustment: "Hijri adjustment",
    hijriAdjustmentHelp: "Use this if your local moon sighting differs by a day.",
    language: "Language",
    followSystem: "Follow system",
    location: "Location",
    mode: "Mode",
    automatic: "Automatic",
    manual: "Manual",
    detectMyLocation: "Detect my location",
    locationUnavailable: "Location is not available on this device.",
    couldNotDetectLocation: "Could not detect your location.",
    detecting: "Detecting",
    detect: "Detect",
    latitude: "Latitude",
    longitude: "Longitude",
    elevationMeters: "Elevation (m)",
    masterTimezone: "Master timezone",
    timezone: "Timezone",
    followSystemTimezone: "Follow system",
    pickExplicitly: "Pick explicitly",
    resolved: "Resolved",
    source: "Source",
    timeSource: "Time source",
    calculated: "Calculated",
    manualFixed: "Manual (fixed)",
    method: "Method",
    calculationMethod: "Calculation method",
    asrMadhab: "Asr (madhab)",
    standard: "Standard",
    hanafi: "Hanafi",
    highLatitudeRule: "High-latitude rule",
    automaticRecommended: "Automatic (recommended)",
    none: "None",
    middleOfNight: "Middle of night",
    oneSeventh: "One-seventh",
    angleBased: "Angle-based",
    automation: "Automation",
    autoDetectMethod: "Auto-detect method from location",
    detectedMethod: "Detected method",
    methodHint: ({ country }: Record<string, string | number>) => country ? `Suggested for ${country}` : "Suggested from your region",
    manualFixedSchedule: "Manual fixed schedule",
    status: "Status",
    manualScheduleHelp: "Editing any jamaat time switches the app to Manual fixed mode.",
    active: "Active",
    useManualSchedule: "Use manual schedule",
    adhanBeforeJamaat: "Adhan before jamaat",
    blockScreenAtPrayerTime: "Block screen at prayer time",
    blockScreenHelp: "Uses Focus Mode at the exact manual jamaat time.",
    master: "Master",
    enableNotifications: "Enable notifications",
    notificationsHelp: "Master switch for all prayer alerts.",
    sample: "Sample",
    sendSample: "Send sample",
    sampleBody: "Sample prayer notification from the Windows app.",
    defaults: "Defaults",
    defaultSound: "Default sound",
    previewSound: "Preview sound",
    playFullAdhanAudio: "Play full Adhan audio",
    earlyReminder: "Early reminder",
    iqamahReminder: "Iqamah reminder",
    perPrayer: "Per prayer",
    atTime: "At time",
    adhan: "Adhan",
    before: "Before",
    prayerDuration: "Prayer duration",
    blurIntensity: "Blur intensity",
    triggerOn: "Trigger on",
    emergencyExit: "Emergency exit",
    emergencyExitHelp: "Allow Esc to exit early on Windows.",
    tryItForTenSeconds: "Try it for 10 seconds",
    enableFocusMode: "Enable Focus Mode",
    focusModeHelp: "Covers the entire screen during prayer time.",
    behaviour: "Behaviour",
    low: "Low",
    medium: "Medium",
    high: "High",
    opaque: "Opaque",
    obligatoryPrayers: "Obligatory prayers",
    allPrayerTimes: "All prayer times",
    fajrIshaOnly: "Fajr & Isha only",
    firstRunSetup: "First run setup",
    setYourLocation: "Set Your Location",
    setLocationBody: "Use automatic location detection or enter coordinates manually so prayer times match your city.",
    useAutomatic: "Use automatic",
    chooseCalculation: "Choose Calculation",
    keepPrayerAlertsOn: "Keep Prayer Alerts On",
    keepPrayerAlertsBody: "Windows notifications, reminders, tray access, Focus Mode, and Adhan playback are ready to use.",
    skip: "Skip",
    back: "Back",
    nextButton: "Next",
    finish: "Finish",
    prayerInProgress: "Prayer in progress",
    focusPauseBody: "Pause, make wudu, and step away from the screen.",
    pressEscToExit: "Press Esc to exit early",
    iconOnly: "Icon only",
    iconCountdown: "Icon + countdown",
    iconNameCountdown: "Icon + name + countdown",
    nextPrayerClock: "Name + time",
    currentWaqt: "Current waqt",
    iconNameClock: "Icon + name + time",
    countdownOnly: "Countdown only",
    nextPrayerCountdown: "Name + countdown",
    softChime: "Soft chime",
    defaultSoundName: "Default",
    adhanMakkah: "Adhan (Makkah)",
    adhanMadinah: "Adhan (Madinah)",
    off: "Off",
    minutesBefore: ({ minutes }: Record<string, string | number>) => `${minutes} min before`,
    minutesAfter: ({ minutes }: Record<string, string | number>) => `${minutes} min after`,
    detectedCountry: "Detected region",
    systemDetected: "System detected",
  },
  ar: {
    appTitle: "مواقيت الصلاة لويندوز",
    waiting: "بانتظار",
    general: "عام",
    locationTime: "الموقع والوقت",
    calculation: "الحساب",
    notifications: "التنبيهات",
    focusMode: "وضع التركيز",
    nextPrayer: "الصلاة القادمة",
    next: "التالي",
    in: "خلال",
    focusNow: "ابدأ التركيز",
    stop: "إيقاف",
    settings: "الإعدادات",
    quit: "خروج",
    startup: "التشغيل",
    launchAtLogin: "التشغيل عند تسجيل الدخول",
    desktopWidget: "الودجت",
    showFloatingWidget: "إظهار الودجت العائم",
    widgetDescription: "ودجت سطح مكتب يعرض الصلاة القادمة والعد التنازلي.",
    widgetControls: "التحكم بالودجت",
    widgetControlsHelp: "اسحب الودجت من جسمه. استخدم زر X لإخفائه.",
    showNow: "إظهار الآن",
    menuBar: "عنوان شريط النظام",
    labelStyle: "نمط العنوان",
    countdownShows: "يعرض العد",
    panel: "اللوحة",
    showIshraqTime: "إظهار وقت الإشراق",
    showHijriDate: "إظهار التاريخ الهجري",
    hijriAdjustment: "تعديل الهجري",
    hijriAdjustmentHelp: "استخدم هذا إذا كان الرصد المحلي يختلف بيوم.",
    language: "اللغة",
    followSystem: "اتبع النظام",
    location: "الموقع",
    mode: "الوضع",
    automatic: "تلقائي",
    manual: "يدوي",
    detectMyLocation: "اكتشف موقعي",
    locationUnavailable: "الموقع غير متاح على هذا الجهاز.",
    couldNotDetectLocation: "تعذر اكتشاف موقعك.",
    detecting: "جارٍ الاكتشاف",
    detect: "اكتشف",
    latitude: "خط العرض",
    longitude: "خط الطول",
    elevationMeters: "الارتفاع (م)",
    masterTimezone: "المنطقة الزمنية الأساسية",
    timezone: "المنطقة الزمنية",
    followSystemTimezone: "اتبع النظام",
    pickExplicitly: "اختر يدويًا",
    resolved: "المعتمدة",
    source: "المصدر",
    timeSource: "مصدر الوقت",
    calculated: "محسوب",
    manualFixed: "يدوي (ثابت)",
    method: "الطريقة",
    calculationMethod: "طريقة الحساب",
    asrMadhab: "العصر (المذهب)",
    standard: "قياسي",
    hanafi: "حنفي",
    highLatitudeRule: "قاعدة خطوط العرض العالية",
    automaticRecommended: "تلقائي (موصى به)",
    none: "بدون",
    middleOfNight: "منتصف الليل",
    oneSeventh: "سبع الليل",
    angleBased: "حسب الزاوية",
    automation: "الأتمتة",
    autoDetectMethod: "اكتشاف الطريقة تلقائيًا من الموقع",
    detectedMethod: "الطريقة المكتشفة",
    methodHint: ({ country }: Record<string, string | number>) => country ? `مقترحة لـ ${country}` : "مقترحة من منطقتك",
    manualFixedSchedule: "الجدول اليدوي الثابت",
    status: "الحالة",
    manualScheduleHelp: "تعديل أي وقت إقامة ينقل التطبيق للوضع اليدوي الثابت.",
    active: "نشط",
    useManualSchedule: "استخدم الجدول اليدوي",
    adhanBeforeJamaat: "الأذان قبل الجماعة",
    blockScreenAtPrayerTime: "حجب الشاشة وقت الصلاة",
    blockScreenHelp: "يستخدم وضع التركيز عند وقت الجماعة اليدوي بالضبط.",
    master: "عام",
    enableNotifications: "تفعيل التنبيهات",
    notificationsHelp: "المفتاح الرئيسي لكل تنبيهات الصلاة.",
    sample: "تجربة",
    sendSample: "إرسال تجربة",
    sampleBody: "إشعار تجريبي من تطبيق الصلاة على ويندوز.",
    defaults: "الافتراضيات",
    defaultSound: "الصوت الافتراضي",
    previewSound: "معاينة الصوت",
    playFullAdhanAudio: "تشغيل الأذان كاملًا",
    earlyReminder: "تذكير مبكر",
    iqamahReminder: "تذكير الإقامة",
    perPrayer: "لكل صلاة",
    atTime: "في الوقت",
    adhan: "أذان",
    before: "قبل",
    prayerDuration: "مدة الصلاة",
    blurIntensity: "شدة التعتيم",
    triggerOn: "يعمل عند",
    emergencyExit: "خروج طارئ",
    emergencyExitHelp: "السماح بزر Esc للخروج المبكر على ويندوز.",
    tryItForTenSeconds: "جرّبه لمدة 10 ثوانٍ",
    enableFocusMode: "تفعيل وضع التركيز",
    focusModeHelp: "يغطي الشاشة بالكامل وقت الصلاة.",
    behaviour: "السلوك",
    low: "منخفض",
    medium: "متوسط",
    high: "عالٍ",
    opaque: "معتم",
    obligatoryPrayers: "الصلوات المفروضة",
    allPrayerTimes: "كل أوقات الصلاة",
    fajrIshaOnly: "الفجر والعشاء فقط",
    firstRunSetup: "إعداد التشغيل الأول",
    setYourLocation: "حدد موقعك",
    setLocationBody: "استخدم الاكتشاف التلقائي أو أدخل الإحداثيات يدويًا حتى تطابق المواقيت مدينتك.",
    useAutomatic: "استخدم التلقائي",
    chooseCalculation: "اختر الحساب",
    keepPrayerAlertsOn: "أبقِ تنبيهات الصلاة مفعلة",
    keepPrayerAlertsBody: "تنبيهات ويندوز والتذكيرات وصينية النظام ووضع التركيز وتشغيل الأذان جاهزة للاستخدام.",
    skip: "تخطي",
    back: "رجوع",
    nextButton: "التالي",
    finish: "إنهاء",
    prayerInProgress: "الصلاة جارية",
    focusPauseBody: "توقف قليلًا، توضأ، وابتعد عن الشاشة.",
    pressEscToExit: "اضغط Esc للخروج المبكر",
    iconOnly: "أيقونة فقط",
    iconCountdown: "أيقونة + عد تنازلي",
    iconNameCountdown: "أيقونة + اسم + عد تنازلي",
    nextPrayerClock: "اسم + وقت",
    currentWaqt: "الوقت الحالي",
    iconNameClock: "أيقونة + اسم + وقت",
    countdownOnly: "عد تنازلي فقط",
    nextPrayerCountdown: "اسم + عد تنازلي",
    softChime: "جرس خفيف",
    defaultSoundName: "افتراضي",
    adhanMakkah: "أذان (مكة)",
    adhanMadinah: "أذان (المدينة)",
    off: "إيقاف",
    minutesBefore: ({ minutes }: Record<string, string | number>) => `قبل ${minutes} دقيقة`,
    minutesAfter: ({ minutes }: Record<string, string | number>) => `بعد ${minutes} دقيقة`,
    detectedCountry: "المنطقة المكتشفة",
    systemDetected: "اكتشفها النظام",
  },
  tr: {
    appTitle: "Windows Icin Namaz Vakitleri",
    waiting: "Bekleniyor",
    general: "Genel",
    locationTime: "Konum ve Saat",
    calculation: "Hesaplama",
    notifications: "Bildirimler",
    focusMode: "Odak Modu",
    nextPrayer: "Siradaki namaz",
    next: "Sonraki",
    in: "kala",
    focusNow: "Simdi odaklan",
    stop: "Durdur",
    settings: "Ayarlar",
    quit: "Cikis",
    startup: "Baslangic",
    launchAtLogin: "Oturum acinca baslat",
    desktopWidget: "Masaustu bileceni",
    showFloatingWidget: "Yuzer bileceni goster",
    widgetDescription: "Siradaki namaz ve geri sayim icin masaustu bileceni.",
    widgetControls: "Bilecen denetimleri",
    widgetControlsHelp: "Bileceni govdesinden surukleyin. Gizlemek icin X dugmesini kullanin.",
    showNow: "Simdi goster",
    menuBar: "Tepsi etiketi",
    labelStyle: "Etiket stili",
    countdownShows: "Geri sayim gosterimi",
    panel: "Panel",
    showIshraqTime: "Israk vaktini goster",
    showHijriDate: "Hicri tarihi goster",
    hijriAdjustment: "Hicri duzeltme",
    hijriAdjustmentHelp: "Yerel ru'yet bir gun farkliysa bunu kullanin.",
    language: "Dil",
    followSystem: "Sistemi takip et",
    location: "Konum",
    mode: "Mod",
    automatic: "Otomatik",
    manual: "Elle",
    detectMyLocation: "Konumumu bul",
    locationUnavailable: "Bu cihazda konum kullanilamiyor.",
    couldNotDetectLocation: "Konumunuz algilanamadi.",
    detecting: "Algilaniyor",
    detect: "Bul",
    latitude: "Enlem",
    longitude: "Boylam",
    elevationMeters: "Rakim (m)",
    masterTimezone: "Ana saat dilimi",
    timezone: "Saat dilimi",
    followSystemTimezone: "Sistemi takip et",
    pickExplicitly: "Elle sec",
    resolved: "Kullanilan",
    source: "Kaynak",
    timeSource: "Vakit kaynagi",
    calculated: "Hesaplanan",
    manualFixed: "Elle (sabit)",
    method: "Yontem",
    calculationMethod: "Hesaplama yontemi",
    asrMadhab: "Ikindi (mezhep)",
    standard: "Standart",
    hanafi: "Hanefi",
    highLatitudeRule: "Yuksek enlem kurali",
    automaticRecommended: "Otomatik (onerilen)",
    none: "Yok",
    middleOfNight: "Gecenin ortasi",
    oneSeventh: "Yedide bir",
    angleBased: "Aci tabanli",
    automation: "Otomasyon",
    autoDetectMethod: "Yontemi konumdan otomatik belirle",
    detectedMethod: "Algilanan yontem",
    methodHint: ({ country }: Record<string, string | number>) => country ? `${country} icin onerilir` : "Bolgenize gore onerildi",
    manualFixedSchedule: "Sabit manuel cemaat cizelgesi",
    status: "Durum",
    manualScheduleHelp: "Herhangi bir cemaat saatini duzenlemek uygulamayi manuel sabit moda alir.",
    active: "Etkin",
    useManualSchedule: "Manuel cizelgeyi kullan",
    adhanBeforeJamaat: "Cemaatten once ezan",
    blockScreenAtPrayerTime: "Namaz vaktinde ekrani kapat",
    blockScreenHelp: "Tam manuel cemaat saatinde Odak Modu kullanir.",
    master: "Ana",
    enableNotifications: "Bildirimleri ac",
    notificationsHelp: "Tum namaz uyarilari icin ana anahtar.",
    sample: "Ornek",
    sendSample: "Ornek gonder",
    sampleBody: "Windows uygulamasindan ornek namaz bildirimi.",
    defaults: "Varsayilanlar",
    defaultSound: "Varsayilan ses",
    previewSound: "Sesi dene",
    playFullAdhanAudio: "Tam ezan sesi cal",
    earlyReminder: "Erken hatirlatici",
    iqamahReminder: "Kamet hatirlaticisi",
    perPrayer: "Namaz bazinda",
    atTime: "Vaktinde",
    adhan: "Ezan",
    before: "Once",
    prayerDuration: "Namaz suresi",
    blurIntensity: "Bulaniklik siddeti",
    triggerOn: "Tetikleme",
    emergencyExit: "Acil cikis",
    emergencyExitHelp: "Windows'ta erken cikis icin Esc tusuna izin ver.",
    tryItForTenSeconds: "10 saniye dene",
    enableFocusMode: "Odak Modunu etkinlestir",
    focusModeHelp: "Namaz vaktinde tum ekrani kaplar.",
    behaviour: "Davranis",
    low: "Dusuk",
    medium: "Orta",
    high: "Yuksek",
    opaque: "Tam opak",
    obligatoryPrayers: "Farz namazlar",
    allPrayerTimes: "Tum vakitler",
    fajrIshaOnly: "Sadece sabah ve yatsi",
    firstRunSetup: "Ilk kurulum",
    setYourLocation: "Konumunuzu ayarlayin",
    setLocationBody: "Namaz vakitleri sehrinize uysun diye otomatik konum algilamayi kullanin veya koordinatlari elle girin.",
    useAutomatic: "Otomatigi kullan",
    chooseCalculation: "Hesaplamayi secin",
    keepPrayerAlertsOn: "Namaz uyarilarini acik tutun",
    keepPrayerAlertsBody: "Windows bildirimleri, hatirlaticilar, tepsi erisimi, Odak Modu ve ezan oynatma kullanima hazir.",
    skip: "Gec",
    back: "Geri",
    nextButton: "Ileri",
    finish: "Bitir",
    prayerInProgress: "Namaz suruyor",
    focusPauseBody: "Durun, abdest alin ve ekrandan uzaklasin.",
    pressEscToExit: "Erken cikmak icin Esc basin",
    iconOnly: "Sadece simge",
    iconCountdown: "Simge + geri sayim",
    iconNameCountdown: "Simge + ad + geri sayim",
    nextPrayerClock: "Ad + saat",
    currentWaqt: "Gecerli vakit",
    iconNameClock: "Simge + ad + saat",
    countdownOnly: "Sadece geri sayim",
    nextPrayerCountdown: "Ad + geri sayim",
    softChime: "Yumusak zil",
    defaultSoundName: "Varsayilan",
    adhanMakkah: "Ezan (Mekke)",
    adhanMadinah: "Ezan (Medine)",
    off: "Kapali",
    minutesBefore: ({ minutes }: Record<string, string | number>) => `${minutes} dk once`,
    minutesAfter: ({ minutes }: Record<string, string | number>) => `${minutes} dk sonra`,
    detectedCountry: "Algilanan bolge",
    systemDetected: "Sistem algiladi",
  },
  bn: {
    appTitle: "উইন্ডোজের জন্য নামাজের সময়",
    waiting: "অপেক্ষা করছে",
    general: "সাধারণ",
    locationTime: "লোকেশন ও সময়",
    calculation: "হিসাব",
    notifications: "নোটিফিকেশন",
    focusMode: "ফোকাস মোড",
    nextPrayer: "পরবর্তী নামাজ",
    next: "পরবর্তী",
    in: "বাকি",
    focusNow: "এখন ফোকাস",
    stop: "বন্ধ",
    settings: "সেটিংস",
    quit: "বন্ধ করুন",
    startup: "স্টার্টআপ",
    launchAtLogin: "লগইনে চালু হবে",
    desktopWidget: "ডেস্কটপ উইজেট",
    showFloatingWidget: "ফ্লোটিং উইজেট দেখান",
    widgetDescription: "পরবর্তী নামাজ ও কাউন্টডাউনসহ ডেস্কটপ উইজেট।",
    widgetControls: "উইজেট নিয়ন্ত্রণ",
    widgetControlsHelp: "উইজেটের বডি ধরে টানুন। লুকাতে X ব্যবহার করুন।",
    showNow: "এখন দেখান",
    menuBar: "ট্রে লেবেল",
    labelStyle: "লেবেল স্টাইল",
    countdownShows: "কাউন্টডাউনে দেখাবে",
    panel: "প্যানেল",
    showIshraqTime: "ইশরাক সময় দেখান",
    showHijriDate: "হিজরি তারিখ দেখান",
    hijriAdjustment: "হিজরি সমন্বয়",
    hijriAdjustmentHelp: "স্থানীয় চাঁদ দেখার সাথে এক দিন পার্থক্য হলে এটি ব্যবহার করুন।",
    language: "ভাষা",
    followSystem: "সিস্টেম অনুসরণ",
    location: "লোকেশন",
    mode: "মোড",
    automatic: "অটোমেটিক",
    manual: "ম্যানুয়াল",
    detectMyLocation: "আমার লোকেশন শনাক্ত করুন",
    locationUnavailable: "এই ডিভাইসে লোকেশন পাওয়া যাচ্ছে না।",
    couldNotDetectLocation: "আপনার লোকেশন শনাক্ত করা যায়নি।",
    detecting: "শনাক্ত হচ্ছে",
    detect: "শনাক্ত করুন",
    latitude: "অক্ষাংশ",
    longitude: "দ্রাঘিমাংশ",
    elevationMeters: "উচ্চতা (মি)",
    masterTimezone: "মূল টাইমজোন",
    timezone: "টাইমজোন",
    followSystemTimezone: "সিস্টেম অনুসরণ",
    pickExplicitly: "নিজে বাছুন",
    resolved: "চলমান",
    source: "উৎস",
    timeSource: "সময় উৎস",
    calculated: "হিসাবকৃত",
    manualFixed: "ম্যানুয়াল (স্থির)",
    method: "পদ্ধতি",
    calculationMethod: "হিসাবের পদ্ধতি",
    asrMadhab: "আসর (মাযহাব)",
    standard: "স্ট্যান্ডার্ড",
    hanafi: "হানাফি",
    highLatitudeRule: "উচ্চ অক্ষাংশ নিয়ম",
    automaticRecommended: "অটোমেটিক (প্রস্তাবিত)",
    none: "কোনওটি নয়",
    middleOfNight: "রাতের মাঝামাঝি",
    oneSeventh: "সাতভাগের একভাগ",
    angleBased: "এঙ্গেল-ভিত্তিক",
    automation: "অটোমেশন",
    autoDetectMethod: "লোকেশন থেকে পদ্ধতি স্বয়ংক্রিয়ভাবে ঠিক করুন",
    detectedMethod: "শনাক্ত পদ্ধতি",
    methodHint: ({ country }: Record<string, string | number>) => country ? `${country} এর জন্য প্রস্তাবিত` : "আপনার অঞ্চলের ভিত্তিতে প্রস্তাবিত",
    manualFixedSchedule: "ম্যানুয়াল স্থির সূচি",
    status: "অবস্থা",
    manualScheduleHelp: "যে কোনও জামাত সময় বদলালে অ্যাপ ম্যানুয়াল মোডে চলে যাবে।",
    active: "চালু",
    useManualSchedule: "ম্যানুয়াল সূচি ব্যবহার করুন",
    adhanBeforeJamaat: "জামাতের আগে আজান",
    blockScreenAtPrayerTime: "নামাজের সময় স্ক্রিন ব্লক করুন",
    blockScreenHelp: "ম্যানুয়াল জামাত সময়েই ফোকাস মোড চালু হবে।",
    master: "মূল",
    enableNotifications: "নোটিফিকেশন চালু",
    notificationsHelp: "সব নামাজ সতর্কতার জন্য মাস্টার সুইচ।",
    sample: "স্যাম্পল",
    sendSample: "স্যাম্পল পাঠান",
    sampleBody: "উইন্ডোজ অ্যাপ থেকে স্যাম্পল নামাজ নোটিফিকেশন।",
    defaults: "ডিফল্ট",
    defaultSound: "ডিফল্ট সাউন্ড",
    previewSound: "সাউন্ড শুনুন",
    playFullAdhanAudio: "পূর্ণ আজান চালান",
    earlyReminder: "আগাম স্মরণ",
    iqamahReminder: "ইকামাহ স্মরণ",
    perPrayer: "প্রতি নামাজ",
    atTime: "সময় হলে",
    adhan: "আজান",
    before: "আগে",
    prayerDuration: "নামাজের সময়কাল",
    blurIntensity: "ব্লার মাত্রা",
    triggerOn: "চালু হবে",
    emergencyExit: "জরুরি প্রস্থান",
    emergencyExitHelp: "উইন্ডোজে Esc চেপে আগে বের হওয়া যাবে।",
    tryItForTenSeconds: "১০ সেকেন্ড ট্রাই করুন",
    enableFocusMode: "ফোকাস মোড চালু করুন",
    focusModeHelp: "নামাজের সময় পুরো স্ক্রিন ঢেকে দেয়।",
    behaviour: "আচরণ",
    low: "কম",
    medium: "মাঝারি",
    high: "উচ্চ",
    opaque: "অস্বচ্ছ",
    obligatoryPrayers: "ফরজ নামাজ",
    allPrayerTimes: "সব নামাজের সময়",
    fajrIshaOnly: "শুধু ফজর ও ইশা",
    firstRunSetup: "প্রথমবার সেটআপ",
    setYourLocation: "আপনার লোকেশন ঠিক করুন",
    setLocationBody: "অটোমেটিক লোকেশন বা ম্যানুয়াল কোঅর্ডিনেট ব্যবহার করুন যাতে সময় আপনার শহরের সঙ্গে মিলে।",
    useAutomatic: "অটোমেটিক ব্যবহার করুন",
    chooseCalculation: "হিসাব পদ্ধতি বাছুন",
    keepPrayerAlertsOn: "নামাজ সতর্কতা চালু রাখুন",
    keepPrayerAlertsBody: "উইন্ডোজ নোটিফিকেশন, রিমাইন্ডার, ট্রে অ্যাক্সেস, ফোকাস মোড, আর আজান প্লেব্যাক প্রস্তুত।",
    skip: "এড়িয়ে যান",
    back: "পেছনে",
    nextButton: "পরবর্তী",
    finish: "শেষ",
    prayerInProgress: "নামাজ চলছে",
    focusPauseBody: "একটু থামুন, ওযু করুন, এবং স্ক্রিন থেকে দূরে যান।",
    pressEscToExit: "আগে বের হতে Esc চাপুন",
    iconOnly: "শুধু আইকন",
    iconCountdown: "আইকন + কাউন্টডাউন",
    iconNameCountdown: "আইকন + নাম + কাউন্টডাউন",
    nextPrayerClock: "নাম + সময়",
    currentWaqt: "বর্তমান ওয়াক্ত",
    iconNameClock: "আইকন + নাম + সময়",
    countdownOnly: "শুধু কাউন্টডাউন",
    nextPrayerCountdown: "নাম + কাউন্টডাউন",
    softChime: "নরম চাইম",
    defaultSoundName: "ডিফল্ট",
    adhanMakkah: "আজান (মক্কা)",
    adhanMadinah: "আজান (মদিনা)",
    off: "বন্ধ",
    minutesBefore: ({ minutes }: Record<string, string | number>) => `${minutes} মিনিট আগে`,
    minutesAfter: ({ minutes }: Record<string, string | number>) => `${minutes} মিনিট পরে`,
    detectedCountry: "শনাক্ত অঞ্চল",
    systemDetected: "সিস্টেম শনাক্ত করেছে",
  },
} satisfies Record<SupportedLanguage, Record<string, TranslationValue>>;

const prayerTranslations: Record<SupportedLanguage, Record<Prayer, string>> = {
  en: { fajr: "Fajr", sunrise: "Sunrise", dhuhr: "Dhuhr", asr: "Asr", maghrib: "Maghrib", isha: "Isha" },
  ar: { fajr: "الفجر", sunrise: "الشروق", dhuhr: "الظهر", asr: "العصر", maghrib: "المغرب", isha: "العشاء" },
  tr: { fajr: "Imsak", sunrise: "Gunes", dhuhr: "Ogle", asr: "Ikindi", maghrib: "Aksam", isha: "Yatsi" },
  bn: { fajr: "ফজর", sunrise: "সূর্যোদয়", dhuhr: "যোহর", asr: "আসর", maghrib: "মাগরিব", isha: "ইশা" },
};

export type TranslationKey = keyof typeof translations.en;

export function resolveLanguage(languageOverride?: string): SupportedLanguage {
  if (languageOverride && languageOverride in translations) {
    return languageOverride as SupportedLanguage;
  }
  const browserLocales = [...(navigator.languages ?? []), navigator.language].filter(Boolean);
  for (const locale of browserLocales) {
    const base = locale.toLowerCase().split("-")[0];
    if (base in translations) return base as SupportedLanguage;
  }
  return "en";
}

export function textDirection(language: SupportedLanguage): "ltr" | "rtl" {
  return language === "ar" ? "rtl" : "ltr";
}

export function t(language: SupportedLanguage, key: TranslationKey, vars: Record<string, string | number> = {}): string {
  const value = translations[language][key] ?? translations.en[key];
  return typeof value === "function" ? value(vars) : value;
}

export function prayerLabel(language: SupportedLanguage, prayer: Prayer): string {
  return prayerTranslations[language][prayer] ?? prayerTranslations.en[prayer];
}

export function formatHijriDateLocalized(date: Date, dayAdjustment: number, timeZone: string, language: SupportedLanguage): string {
  const adjusted = new Date(date.getTime() + Math.round(dayAdjustment) * 86_400_000);
  try {
    return new Intl.DateTimeFormat(`${language}-u-ca-islamic-umalqura`, {
      calendar: "islamic-umalqura",
      day: "numeric",
      month: "long",
      year: "numeric",
      timeZone,
    }).format(adjusted);
  } catch {
    try {
      return new Intl.DateTimeFormat(language, {
        calendar: "islamic-umalqura",
        day: "numeric",
        month: "long",
        year: "numeric",
        timeZone,
      }).format(adjusted);
    } catch {
      return "";
    }
  }
}

export function buildTrayLabel(
  language: SupportedLanguage,
  style: MenuBarStyle,
  countdownMode: MenuBarCountdownMode,
  prayer: Prayer | undefined,
  seconds: number,
  prayerTimeLabel: string,
  countdownLabel: string,
): string {
  if (!prayer) return t(language, "appTitle");
  const prayerName = prayerLabel(language, prayer);
  const pieces = {
    countdown: countdownLabel,
    nameCountdown: `${prayerName} ${t(language, "in")} ${countdownLabel}`,
    nameClock: `${prayerName} ${prayerTimeLabel}`,
  };

  switch (style) {
    case "iconOnly":
      return "☪";
    case "countdownOnly":
      return countdownLabel;
    case "iconCountdown":
      return `☪ ${countdownLabel}`;
    case "nextPrayerCountdown":
      return countdownMode === "currentWaqt" ? `${prayerName} ${countdownLabel}` : pieces.nameCountdown;
    case "nextPrayerClock":
      return pieces.nameClock;
    case "iconNameClock":
      return `☪ ${pieces.nameClock}`;
    case "iconNameCountdown":
      return `☪ ${countdownMode === "currentWaqt" ? `${prayerName} ${countdownLabel}` : pieces.nameCountdown}`;
    default:
      return pieces.nameCountdown;
  }
}
